--- #YAML:1.0
name:               Auth-Yubikey_WebClient
version:            2.01
abstract:           Authenticating the Yubikey against the Yubico Web API
author:
    - Phil Massyn <phil@massyn.net>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Digest::HMAC_SHA1:  1
    LWP::Simple:        1
    MIME::Base64:       1
    Test::More:         0
    URI::Escape:        1
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
